# Generated by Django 3.0.7 on 2020-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('method', models.TextField()),
                ('headers', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
